### ISSUE TITLE
My java problem

### ISSUE THREAD

**Issue by guile-clarusway** [guile-clarusway/Programming-Languages#2]
I can't print my name with the code like "This is Guile!"

![smple](https://user-images.githubusercontent.com/59561051/72158676-d6012b80-33cb-11ea-9e18-39ef416d1b69.png)

**Comment by namikkaplansw** [comment]
Hi There,
I advise you to insert a line something like this,
System.out.println("This is Guile");
I hope this solves your problem, good luck

**Comment by guile-clarusway** [comment]
It worked for the issue #2
